FROM index.tenxcloud.com/ericuni/base:latest

RUN apt-get install -y --no-install-recommends \
	build-essential \
	cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev \
	python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

CMD ["/bin/bash"]

